### ISSUE TITLE
[Bug] Percent. of exams assessed as failed should not include people who didn't attend exam

### ISSUE THREAD

**Issue by Espresso-Kp** [mcmikecreations/tum_info#194]
Greetings, 

I remember that the failure rate used to be calculated excluding people who did not take the exam. It seems to have changed now, and I'm not sure if this is intentional, but I believe the previous calculation made more sense.

Thank you for your efforts with this site, it has helped me a lot!

Thanks!
Kai

**Comment by mcmikecreations** [comment]
I did push some changes to allow Pass/Fail without a grade, maybe this messed up the other formulas. I'll take a look, thanks!
